feat: analytics, view transitions, website image, and more (#420)

diff --git a/apps/website/Dockerfile b/apps/website/Dockerfile
--- a/apps/website/Dockerfile
+++ b/apps/website/Dockerfile
@@ -42,12 +42,25 @@ RUN --mount=type=bind,source=package.json,target=package.json \
 COPY --from=builder /src/out/full/ .
 COPY turbo.json turbo.json
 
+# Declare necessary environment variables for the build step.
+ARG NEXT_PUBLIC_SITE_URL
+
+RUN \
+	if [ -z "$NEXT_PUBLIC_SITE_URL" ]; then \
+		echo "ERROR: NEXT_PUBLIC_SITE_URL build-arg is required" >&2; \
+		exit 1; \
+	fi
+
+ARG NEXT_PUBLIC_UMAMI_ID
+ARG NEXT_PUBLIC_UMAMI_URL
+
 ENV NEXT_TELEMETRY_DISABLED=1
 ENV TURBO_TELEMETRY_DISABLED=1
 RUN turbo run build --filter=@ticketer/website
 
 # Copy the files over and use the apps/website directory.
 FROM base AS runner
+RUN apk add --no-cache curl
 WORKDIR /src
 USER node
 
@@ -58,8 +71,9 @@ COPY --from=installer --chown=node:node /src/apps/website/.next/standalone ./
 COPY --from=installer --chown=node:node /src/apps/website/.next/static ./apps/website/.next/static
 COPY --from=installer --chown=node:node /src/apps/website/public ./apps/website/public
 
+ENV HOSTNAME=0.0.0.0
 ENV PORT=2027
-EXPOSE 2027
+EXPOSE ${PORT}
 
 # Run the website.
 CMD ["node", "apps/website/server.js"]
